/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package storylangc;

import storylangc.lexer.SLL;

public class App {

    public static void main(String[] args) {
        SLL sll = new SLL("src/main/resources/ExampleProjectA");
        for (String path : sll.getAllFilePaths("src/main/resources/ExampleProjectA")) {
            System.out.println(
                "File: " + path + "\n" +
                "Lines: " + sll.fileToString(path).split(" ")[5] + "\n"
            );
        }
    }
}
