/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package storylangc;

import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.File;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test
    void testGetFileFromResource() {
        // Test with a file that exists in the resources directory
        File file = App.getFileFromResource("existingFile.sl");
        assertNotNull(file);
        assertTrue(file.exists());

        // Test with a file that does not exist in the resources directory
        assertThrows(IllegalArgumentException.class, () -> {
            App.getFileFromResource("nonExistingFile.sl");
        });
    }

    @Test
    void testGetFileFromResourceWithNull() {
        // Test with null input
        assertThrows(NullPointerException.class, () -> {
            App.getFileFromResource(null);
        });
    }

    @Test
    void testGetFileFromPath() {
        // Test with a file that exists in the resources directory
        File file = App.getFileFromPath("app/src/test/resources/existingFile.sl");
        assertNotNull(file);
        assertTrue(file.exists());

        // Test with a file that does not exist in the resources directory
        assertThrows(IllegalArgumentException.class, () -> {
            App.getFileFromPath("app/src/test/resources/nonExistingFile.sl");
        });
    }

    @Test
    void testGetFileFromPathWithNull() {
        // Test with null input
        assertThrows(NullPointerException.class, () -> {
            App.getFileFromPath(null);
        });
    }

}
